components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          title: Detail
          type: array
      title: HTTPValidationError
      type: object
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          title: Location
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
      type: object
info:
  title: argo wrapper
  version: 0.1.0
openapi: 3.1.0
paths:
  /cancel/{workflow_name}:
    post:
      description: cancels a currently running workflow
      operationId: cancel_workflow_cancel__workflow_name__post
      parameters:
      - in: path
        name: workflow_name
        required: true
        schema:
          title: Workflow Name
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                anyOf:
                - type: string
                - {}
                title: Response Cancel Workflow Cancel  Workflow Name  Post
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Cancel Workflow
  /logs/{workflow_name}:
    get:
      description: returns the list of workflows the user has ran
      operationId: get_workflow_logs_logs__workflow_name__get
      parameters:
      - in: path
        name: workflow_name
        required: true
        schema:
          title: Workflow Name
          type: string
      - in: query
        name: uid
        required: true
        schema:
          title: Uid
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                anyOf:
                - items:
                    type: object
                  type: array
                - {}
                title: Response Get Workflow Logs Logs  Workflow Name  Get
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Get Workflow Logs
  /retry/{workflow_name}:
    post:
      description: retries a currently failed workflow
      operationId: retry_workflow_retry__workflow_name__post
      parameters:
      - in: path
        name: workflow_name
        required: true
        schema:
          title: Workflow Name
          type: string
      - in: query
        name: uid
        required: true
        schema:
          title: Uid
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                anyOf:
                - type: string
                - {}
                title: Response Retry Workflow Retry  Workflow Name  Post
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Retry Workflow
  /status/{workflow_name}:
    get:
      description: returns details of a workflow
      operationId: get_workflow_details_status__workflow_name__get
      parameters:
      - in: path
        name: workflow_name
        required: true
        schema:
          title: Workflow Name
          type: string
      - in: query
        name: uid
        required: true
        schema:
          title: Uid
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                anyOf:
                - type: object
                - type: string
                - {}
                title: Response Get Workflow Details Status  Workflow Name  Get
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Get Workflow Details
  /submit:
    post:
      description: route to submit workflow
      operationId: submit_workflow_submit_post
      requestBody:
        content:
          application/json:
            schema:
              title: Request Body
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                anyOf:
                - type: string
                - {}
                title: Response Submit Workflow Submit Post
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Submit Workflow
  /test:
    get:
      description: route to test that the argo-workflow is correctly running
      operationId: test_test_get
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: Test
  /workflows:
    get:
      description: returns the list of workflows the user has ran
      operationId: get_workflows_workflows_get
      parameters:
      - in: query
        name: team_projects
        required: false
        schema:
          anyOf:
          - items:
              type: string
            type: array
          - type: 'null'
          title: Team Projects
      responses:
        '200':
          content:
            application/json:
              schema:
                anyOf:
                - items:
                    type: object
                  type: array
                - {}
                title: Response Get Workflows Workflows Get
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Get Workflows
  /workflows/user-monthly:
    get:
      description: 'Query Argo service to see how many successful run user already

        have in the current calendar month. Return workflow numbers and workflow cap'
      operationId: get_user_monthly_workflow_workflows_user_monthly_get
      responses:
        '200':
          content:
            application/json:
              schema:
                title: Response Get User Monthly Workflow Workflows User Monthly Get
                type: object
          description: Successful Response
      summary: Get User Monthly Workflow
