apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  namespace: argo
  annotations:
    workflows.argoproj.io/version: ">= 3.1.0"
  labels:
    workflows.argoproj.io/archive-strategy: "true"
    gen3username: "user-test user"
spec:
  entrypoint: gwas-workflow
  podGC:
    strategy: OnWorkflowSuccess
  nodeSelector:
    role: "workflow"
  tolerations:
    - key: "role"
      operator: "Equal"
      value: "workflow"
      effect: "NoSchedule"
  podMetadata:
    annotations:
      gen3username: "test user"
    labels:
      gen3username: "user-test user"
  arguments:
    parameters:
      - name: cohort_definition_id
        value: 70
      - name: cohort_middleware_url
        value: "http://cohort-middleware-service.default/cohort-data/by-source-id/4/by-cohort-definition-id/70"
      - name: cohort_middleware_body
        value: |-
          {
            "PrefixedConceptIds": ["ID_2000006885", "ID_2000006886", "ID_2000000324"]
          }
      - name: n_pcs
        default: 0
        value: 3
      - name: covariates
        value: ID_2000006886 ID_2000000324
      - name: out_prefix
        value: vadc_genesis
      - name: outcome
        value: ID_2000006885
      - name: outcome_is_binary
        enum:
          - "TRUE"
          - "FALSE"
        default: "FALSE"
        value: "FALSE"
      - name: pca_file
        value: /commons-data/pcs.RData
      - name: relatedness_matrix_file
        value: /commons-data/KINGmatDeg3.RData
      - name: genome_build
        enum:
          - "hg38"
          - "hg19"
        default: "hg19"
        value: "hg19"
      - name: n_segments
        value: 0
      - name: segment_length
        default: 10000
        value: 2000
      - name: variant_block_size
        default: 1024
        value: 100
      - name: mac_threshold
        value: 0
      - name: maf_threshold
        value: 0.01
      - name: imputation_score_cutoff
        value: 0.3
      - name: gds_files
        value: |-
          [
            "/commons-data/gds/chr1.merged.vcf.gz.gds",
            "/commons-data/gds/chr2.merged.vcf.gz.gds",
            "/commons-data/gds/chr3.merged.vcf.gz.gds",
            "/commons-data/gds/chr4.merged.vcf.gz.gds",
            "/commons-data/gds/chr5.merged.vcf.gz.gds",
            "/commons-data/gds/chr6.merged.vcf.gz.gds",
            "/commons-data/gds/chr7.merged.vcf.gz.gds",
            "/commons-data/gds/chr8.merged.vcf.gz.gds",
            "/commons-data/gds/chr9.merged.vcf.gz.gds",
            "/commons-data/gds/chr10.merged.vcf.gz.gds",
            "/commons-data/gds/chr11.merged.vcf.gz.gds",
            "/commons-data/gds/chr12.merged.vcf.gz.gds",
            "/commons-data/gds/chr13.merged.vcf.gz.gds",
            "/commons-data/gds/chr14.merged.vcf.gz.gds",
            "/commons-data/gds/chr15.merged.vcf.gz.gds",
            "/commons-data/gds/chr16.merged.vcf.gz.gds",
            "/commons-data/gds/chr17.merged.vcf.gz.gds",
            "/commons-data/gds/chr18.merged.vcf.gz.gds",
            "/commons-data/gds/chr19.merged.vcf.gz.gds",
            "/commons-data/gds/chr20.merged.vcf.gz.gds",
            "/commons-data/gds/chr21.merged.vcf.gz.gds",
            "/commons-data/gds/chr22.merged.vcf.gz.gds"
          ]
  volumes:
    - name: gateway
      persistentVolumeClaim:
        claimName: va-input-nfs-pvc
    - name: workdir
      emptyDir:
        sizeLimit: "10Gi"

  workflowTemplateRef:
    name: gwas-template-6226080403eb62585981d9782aec0f3a82a7e906
