apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
  labels:
    workflows.argoproj.io/archive-strategy: "false"
  annotations:
    workflows.argoproj.io/description: |
      This is a simple hello world example.
      You can also run it in Python: https://couler-proj.github.io/couler/examples/#hello-world
spec:
  entrypoint: whalesay
  nodeSelector:
    role: "workflow"
  tolerations:
    - key: "role"
      operator: "Equal"
      value: "workflow"
      effect: "NoSchedule"
  pod_metadata:
    labels:
      gen3username: "empty-user-label"
  arguments:
    parameters:
      - name: pheno_csv_key
        value: 5k.prod_height_pheno.csv
      - name: n_pcs
        default: 0
        value: 10
      - name: covariates
        value: gender age Hare
      - name: out_prefix
        default: genesis_vadc
        value: 5k_vhdcprod_height
      - name: outcome
        value: Height
      - name: outcome_is_binary
        enum:
          - "TRUE"
          - "FALSE"
        default: "FALSE"
        value: "FALSE"
      - name: pca_file
        value: /commons-data/pcs.RData
      - name: relatedness_matrix_file
        value: /commons-data/KINGmatDeg3.RData
      - name: genome_build
        enum:
          - "hg38"
          - "hg19"
        default: "hg19"
        value: "hg19"
      - name: n_segments
        value: 0
      - name: segment_length
        default: 10000
        value: 10000
      - name: variant_block_size
        default: 1024
        value: 1024
      - name: mac_threshold
        value: 0
      - name: maf_threshold
        value: 0.01
      - name: imputation_score_cutoff
        value: 0.3
  templates:
  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["{{arguments.parameters.pheno_csv_key}}"]
