name: pytest-coverage
on:
  pull_request:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.4

      - name: Install dependencies
        run: |
          curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
          $HOME/.poetry/bin/poetry install
          pip install .
          python -m pip install --upgrade pip

      - name: Get test coverage and fail if total coverage under 80 percent
        run: |
          pytest --cov argowrapper test --cov-fail-under=80
